// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SWaveshareS3_35_Touch

#include "../ui.h"


lv_obj_t * ui_ScreenYYY = NULL;
lv_obj_t * ui_PanelPage = NULL;
// lv_obj_t * ui_PanelGroup = NULL;
// lv_obj_t * ui_PanelLabel = NULL;
// lv_obj_t * ui_PanelTextArea = NULL;
// event funtions


// build funtions

void ui_GpsStatus_screen_init(lv_obj_t *parentGroupPanel)
{
	// Panel around the page
 	ui_PanelPage = lv_obj_create(parentGroupPanel);
    lv_obj_set_height(ui_PanelPage, lv_pct(100));
    lv_obj_set_width(ui_PanelPage, 330);
	//   lv_obj_set_x(ui_PanelGroup, -16);
	//lv_obj_set_y(ui_PanelPage, 0);
    lv_obj_set_align(ui_PanelPage, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_PanelPage, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PanelPage, LV_OBJ_FLAG_SCROLLABLE);   
	
	// No padding
    lv_obj_set_style_pad_left(ui_PanelPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	// No padding between rows and columns
	lv_obj_set_style_pad_row(ui_PanelPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	// Soft background color
    lv_obj_set_style_bg_color(ui_PanelPage, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPage, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



}

void ui_GpsStatus_screen_destroy(void)
{
    if(ui_PanelPage) 
		lv_obj_del(ui_PanelPage);
}
