// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SWaveshareS3_35_Touch

#ifndef UI_GPSSTATUS_H
#define UI_GPSSTATUS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GpsStatus
extern void ui_GpsStatus_screen_init(lv_obj_t *parentGroupPanel);
extern void ui_GpsStatus_screen_destroy(void);

// CUSTOM VARIABLES
extern lv_obj_t * ui_PanelPage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

