// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SWaveshareS3_35_Touch

#include "../ui.h"

lv_obj_t *UIMainScreen = NULL;
lv_obj_t *UIPageGroupPanel = NULL;

void ui_MainScreen_screen_init(void)
{
	UIMainScreen = lv_scr_act();
	lv_obj_remove_flag(UIMainScreen, LV_OBJ_FLAG_SCROLLABLE);

	// Main page panel group
	UIPageGroupPanel = lv_obj_create(UIMainScreen);
	lv_obj_set_width(UIPageGroupPanel, 320);
	lv_obj_set_height(UIPageGroupPanel, 438);
	lv_obj_set_x(UIPageGroupPanel, 0);
	lv_obj_set_y(UIPageGroupPanel, 0);
	lv_obj_set_align(UIPageGroupPanel, LV_ALIGN_BOTTOM_MID);
	lv_obj_set_flex_flow(UIPageGroupPanel, LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(UIPageGroupPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
	lv_obj_set_scroll_snap_x(UIPageGroupPanel, LV_SCROLL_SNAP_CENTER);
	lv_obj_add_flag(UIPageGroupPanel, LV_OBJ_FLAG_SCROLL_ONE);

	// Transparent background
	lv_obj_set_style_bg_color(UIPageGroupPanel, lv_color_hex(0), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(UIPageGroupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	// No border
	lv_obj_set_style_border_color(UIPageGroupPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_opa(UIPageGroupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

	// No padding
	lv_obj_set_style_pad_left(UIPageGroupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(UIPageGroupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(UIPageGroupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(UIPageGroupPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_MainScreen_screen_destroy(void)
{
	if (UIMainScreen)
		lv_obj_del(UIMainScreen);

	// NULL screen variables
	UIMainScreen = NULL;
	UIPageGroupPanel = NULL;
}
